//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalRegistroIncidencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class distrito
    {
        public int Id { get; set; }
        public string nombre_distrito { get; set; }
        public short cantonId { get; set; }
    
        public virtual canton canton { get; set; }
    }
}
