//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalRegistroIncidencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public short Id_Incidencia { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Dirrecion { get; set; }
        public string Detalle { get; set; }
        public short Tipo_Incidencia_Id { get; set; }
        public short Empresa_Id { get; set; }
        public short Estado_Incidencias_Id { get; set; }
        public short usuario_id { get; set; }
        public byte[] Fotografia1 { get; set; }
    
        public virtual Tipo_Incidencia Tipo_Incidencia { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estado_Incidencias Estado_Incidencia_Id { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
